import { StoryTheme } from "./types";

export const SUB_THEMES: Record<StoryTheme, string[]> = {
  'ceo-reveal': [
    'Chủ tịch giả làm bảo vệ thử lòng nhân viên.',
    'Thiếu gia đi xin việc bị người yêu cũ sỉ nhục.',
    'Chủ tịch giả làm shipper bị khinh thường khi đi họp lớp.',
    'Phu nhân hào môn giả làm giúp việc để tìm con dâu hiền.',
    'CEO ẩn danh đi khảo sát công ty con.',
    'Tiểu thư nhà giàu giả nghèo để thử lòng bạn trai.',
    'Chủ tịch giả tàn tật để xem ai thật lòng với mình.',
    'Cựu chiến binh/Đại úy giải ngũ bị nhà vợ coi thường.',
    'Thiên tài đầu tư giả làm nhân viên quèn.',
    'Bang chủ ẩn cư bị kẻ xấu bắt nạt người thân.',
    'Chủ tịch bị đuổi khỏi nhà và màn trả thù sau 5 năm.',
    'Hợp đồng hôn nhân với tổng tài lạnh lùng.',
    'Thư ký xinh đẹp thực chất là con gái đối thủ.',
    'Chủ tịch đi mua xe bị nhân viên bán hàng đuổi khéo.',
    'Tỷ phú giả làm thợ xây để giúp đỡ dân làng.',
    'Màn "lột xác" của cô gái nghèo sau khi được chủ tịch nâng đỡ.',
    'Tổng tài mất trí nhớ được cô gái nghèo cứu giúp.',
    'Cuộc chiến thừa kế trong gia đình tài phiệt.',
    'Chủ tịch giả làm sinh viên thực tập.',
    'Màn khoe tài sản gây sốc của "người nghèo" nhất phố.'
  ],
  'inspirational': [
    'Hành trình vượt khó của trẻ em vùng cao đi học.',
    'Người khuyết tật trở thành vận động viên chuyên nghiệp.',
    'Khởi nghiệp từ hai bàn tay trắng sau khi phá sản.',
    'Câu chuyện về những người tử tế thầm lặng.',
    'Hành trình giảm cân và thay đổi ngoại hình ngoạn mục.',
    'Người già học đại học hoặc thực hiện ước mơ dang dở.',
    'Bảo vệ môi trường: Những chiến dịch làm sạch biển/rừng.',
    'Lòng tốt giữa người lạ trong xã hội hiện đại.',
    'Vượt qua trầm cảm để sống đời tích cực.',
    'Câu chuyện về những người thầy giáo cắm bản.',
    'Hành trình tìm lại chính mình sau những thất bại.',
    'Bài học về sự trung thực trong kinh doanh.',
    'Sức mạnh của sự kiên trì: Luyện tập 10.000 giờ.',
    'Người mẹ đơn thân nuôi con thành tài.',
    'Câu chuyện về sự sẻ chia trong mùa dịch/thiên tai.',
    'Nuôi dưỡng đam mê từ những điều nhỏ nhất.',
    'Cách đối mặt và vượt qua bạo lực học đường.',
    'Tình bạn xuyên biên giới và những hành động đẹp.',
    'Hành trình chinh phục những đỉnh núi cao nhất.',
    'Những phát minh nhỏ thay đổi cuộc sống người nghèo.'
  ],
  'emotional-family': [
    'Sự hy sinh thầm lặng của người cha.',
    'Nỗi lòng người mẹ chồng và nàng dâu hiện đại.',
    'Tình cảm anh chị em nhường nhịn nhau khi khó khăn.',
    'Chuyện về sự hiếu thảo của con cái đối với cha mẹ già.',
    'Nỗi cô đơn của người già trong viện dưỡng lão.',
    'Hành trình đoàn tụ của những người thân thất lạc.',
    'Sự khác biệt thế hệ giữa ông bà và con cháu.',
    'Tình cảm cha con sau những hiểu lầm quá khứ.',
    'Người vợ tần tảo nuôi chồng ăn học.',
    'Sự gắn kết gia đình qua những bữa cơm chiều.',
    'Cách cha mẹ cùng con vượt qua áp lực thi cử.',
    'Tình yêu của những cặp đôi già vẫn mặn nồng.',
    'Chuyện về những đứa con nuôi và lòng vị tha.',
    'Sự bao dung của gia đình khi con cái lầm lỡ.',
    'Nỗi nhớ quê hương của những người con xa xứ.',
    'Kỷ niệm về những món quà giản dị của ông bà.',
    'Hành trình chuẩn bị Tết đoàn viên.',
    'Sức mạnh gia đình khi có người thân bị bệnh nặng.',
    'Dạy con về lòng nhân ái từ khi còn nhỏ.',
    'Những mâu thuẫn nhỏ nhặt nhưng ấm áp trong nhà.'
  ],
  'comedy': [
    'Những màn troll người yêu "cạn lời".',
    'Thử thách nhịn cười với những tình huống trớ trêu.',
    'Sự khác biệt giữa tưởng tượng và thực tế (Expectation vs Reality).',
    'Những thảm họa vào bếp gây cười.',
    'Khi động vật bắt chước hành động của con người.',
    'Phỏng vấn đường phố với những câu trả lời "khó đỡ".',
    'Màn ảo thuật lỗi và cái kết hài hước.',
    'Những tình huống dở khóc dở cười khi đi phỏng vấn.',
    'Hài kịch tình huống về việc đòi nợ ngày Tết.',
    'Phản ứng của người nước ngoài với đặc sản Việt Nam.',
    'Những cú ngã "đi vào lòng đất".',
    'Troll bạn thân bằng camera giấu kín.',
    'Cuộc sống của hội những người sợ vợ.',
    'Những pha xử lý cồng kềnh của hội chị em.',
    'Khi bố chăm con và cái kết cực lầy.',
    'Học tiếng nước ngoài theo phong cách "Vietsub".',
    'Những kiểu người phổ biến khi đi xem phim/đi xe buýt.',
    'Thử thách ăn những món cay nhất thế giới.',
    'Parody (nhại lại) các bộ phim nổi tiếng.',
    'Những hiểu lầm tai hại do dùng từ địa phương.'
  ],
  'culinary': [
    'Nấu các món ăn siêu to khổng lồ.',
    'Tái hiện món ăn trong phim hoạt hình/truyện tranh.',
    'ASMR âm thanh giòn rụm của các loại đồ chiên.',
    'Hướng dẫn nấu ăn chỉ với 50k mỗi bữa.',
    'Làm các món ăn vặt tuổi thơ tại nhà.',
    'ASMR làm bánh kem và trang trí nghệ thuật.',
    'Nấu ăn kiểu sinh viên với nồi cơm điện.',
    'Khám phá ẩm thực đường phố các vùng miền.',
    'ASMR âm thanh cắt thái rau củ cực mượt.',
    'Tự làm các loại đồ uống trend tại nhà (Trà sữa, cafe muối...).',
    'Quy trình làm các món đặc sản từ khâu thu hoạch.',
    'Nấu ăn theo phong cách "trốn khỏi thành phố" (Chill).',
    'Làm các món chay giả mặn cực giống thật.',
    'ASMR âm thanh nhai kẹo tổ ong/thạch nổ.',
    'Thử thách nấu ăn bằng đồ chơi mini.',
    'Cách bảo quản thực phẩm khoa học trong tủ lạnh.',
    'Trang trí đĩa thức ăn như nhà hàng 5 sao.',
    'Nấu ăn ngoài trời (cắm trại, rừng núi).',
    'Làm các loại mứt và bánh kẹo truyền thống.',
    'ASMR dọn dẹp và sắp xếp nhà bếp ngăn nắp.'
  ],
  'horror': [
    'Giải mã các truyền thuyết đô thị nổi tiếng.',
    'Những câu chuyện tâm linh có thật từ lời kể khán giả.',
    'Review các địa điểm bị đồn có ma ám trên thế giới.',
    'Các hiện tượng kỳ bí chưa có lời giải của khoa học.',
    'Những vụ mất tích bí ẩn trong lịch sử.',
    'Khám phá các căn nhà hoang lúc nửa đêm.',
    'Những giấc mơ tiên tri và sự trùng hợp lạ lùng.',
    'Câu chuyện về các loại bùa chú trong văn hóa dân gian.',
    'Phân tích các tình tiết kinh dị trong phim điện ảnh.',
    'Trải nghiệm các trò chơi gọi hồn (Ouija, Charlie...).',
    'Những bức ảnh chụp được "vật thể lạ" gây tranh cãi.',
    'Câu chuyện về những món đồ cổ bị nguyền rủa.',
    'Sự thật về các vùng đất chết (Tam giác Bermuda, Dyatlov...).',
    'Những âm thanh kỳ lạ dưới lòng đại dương.',
    'Thuyết âm mưu về sự tồn tại của người ngoài hành tinh.',
    'Kể chuyện ma đêm khuya (Podcast kinh dị).',
    'Những phong tục mai táng kỳ lạ của các bộ lạc.',
    'Tâm lý học tội phạm: Bên trong tâm trí kẻ sát nhân.',
    'Những video clip từ camera an ninh ghi lại cảnh kỳ quái.',
    'Trải nghiệm ngủ một mình trong rừng sâu.'
  ],
  'historical': [
    'Nữ chính hiện đại xuyên không thành hoàng hậu thất sủng.',
    'Sát thủ xuyên không về làm tiểu thư phế vật.',
    'Chuyên gia trang điểm về cổ đại trở thành "thánh mỹ phẩm".',
    'Cuộc chiến hậu cung: Mưu kế giữa các phi tần.',
    'Tướng quân lạnh lùng và cô vợ nhỏ tinh nghịch.',
    'Review trang phục cổ phong của các triều đại.',
    'Kiếm hiệp: Hành trình hành hiệp trượng nghĩa của thiếu hiệp.',
    'Bác sĩ hiện đại xuyên không cứu sống hoàng thượng.',
    'Câu chuyện tình yêu ngược tâm giữa người và thần tiên.',
    'Trọng sinh: Quay lại quá khứ để thay đổi vận mệnh.',
    'Thái tử giả làm dân thường đi vi hành.',
    'Màn đối thơ và đấu trí tại tửu lâu cổ đại.',
    'Tình duyên tiền kiếp và sự gặp gỡ ở hiện tại.',
    'Học làm các món ăn cổ truyền theo phong cách cổ trang.',
    'Vương gia phế vật thực chất là cao thủ võ lâm.',
    'Công chúa cải trang nam sinh đi học tại học viện.',
    'Hậu trường làm phim cổ trang: Kỹ xảo và hóa trang.',
    'Những vụ án bí ẩn nơi cung đình.',
    'Xây dựng cơ đồ kinh doanh tại thời cổ đại.',
    'Sự va chạm văn hóa giữa người hiện đại và cổ nhân.'
  ],
  'action': [
    'Những màn rượt đuổi bằng xe mô tô đỉnh cao.',
    'Cảnh sát chìm thâm nhập băng đảng tội phạm.',
    'Võ sĩ đường phố bảo vệ người yếu thế.',
    'Những pha nhào lộn Parkour mạo hiểm trên nhà cao tầng.',
    'Hành trình giải cứu con tin của đặc nhiệm.',
    'Cuộc chiến giữa các băng nhóm vì danh dự.',
    'Phim ngắn võ thuật: Tôn vinh tinh thần võ đạo.',
    'Đặc vụ mất trí nhớ đi tìm lại danh tính.',
    'Những màn đấu súng kịch tính trong rừng rậm.',
    'Vận động viên hành động vượt chướng ngại vật (Ninja Warrior).',
    'Sát thủ chuyên nghiệp quyết định rửa tay gác kiếm.',
    'Cuộc đua xe trái phép và cái kết của sự nông nổi.',
    'Hướng dẫn các đòn thế tự vệ cơ bản khi gặp nguy hiểm.',
    'Hậu trường thực hiện các cảnh quay cháy nổ.',
    'Phim ngắn về đề tài điệp viên nhị trùng.',
    'Cuộc chiến sinh tồn trên đảo hoang.',
    'Săn lùng cổ vật và những cái bẫy chết người.',
    'Cảnh sát giao thông và những pha bắt cướp nghẹt thở.',
    'Hành trình vượt ngục của tù nhân bị oan.',
    'Trận chiến bảo vệ làng quê khỏi đám người xấu.'
  ],
  'sales': [],
  'review': [],
  'tvc': []
};
